ALTER TABLE "TripRecord"
ADD COLUMN "gstRatePerTon" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "TripRecord"
ADD COLUMN "gstPercentage" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "TripRecord"
ADD COLUMN "gstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
